apiVersion: v1
kind: Service
metadata:
  name: spekt8
  labels:
    app: spekt8
spec:
  ports:
    - port: 3000
      nodePort: 30219
      targetPort: spekt8
  selector:
    component: spekt8
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spekt8
spec:
  selector:
    matchLabels:
      component: spekt8
  replicas: 1
  template:
    metadata:
      labels:
        component: spekt8
    spec:
      containers:
        - name: spekt8
          image: elliotxkim/spekt8
          ports:
            - containerPort: 3000